### ISSUE TITLE
ask for database

### ISSUE THREAD

**Issue by satanicman** [dmazlum/Phalcon-Admin-Panel#1]
Hi. I'm new in phalcon framework, and i'm very interested your admin panel realisation. Can you give me your db backup? Or just push it in to repository.

**Comment by dmazlum** [comment]
Hello,

I couldn't find my DB. I deleted it I think. May be you can use my models and create db scheme again. 

Referer links:
https://docs.phalconphp.com/en/latest/reference/tools.html#generating-models
http://stackoverflow.com/questions/21797329/create-a-table-for-phalcon-model

**Comment by satanicman** [comment]
Thanks, I already did this. It look nice, but i am change some things in your project.
